@echo on
adb shell "pm disable-user --user 0 com.samsung.oda.service"
adb shell "pm disable-user --user 0 com.sec.android.RilServiceModeApp"
adb shell "pm disable-user --user 0 com.sec.android.provider.emergencymode"
adb shell "pm disable-user --user 0 com.google.android.overlay.modules.permissioncontroller.forframework"
adb shell "pm disable-user --user 0 com.sec.android.iaft"
adb shell "pm disable-user --user 0 com.samsung.android.app.telephonyui.esimclient"
adb shell "pm disable-user --user 0 com.samsung.android.dsms"
adb shell "pm disable-user --user 0 com.android.dreams.phototable"
adb shell "pm disable-user --user 0 com.samsung.android.mcfds"
adb shell "pm disable-user --user 0 com.samsung.android.smartface.overlay"
adb shell "pm disable-user --user 0 com.samsung.android.knox.kpecore"
adb shell "pm disable-user --user 0 com.samsung.internal.systemui.navbar.sec_gestural_no_hint"
adb shell "pm disable-user --user 0 com.sec.android.app.applinker"
adb shell "pm disable-user --user 0 com.android.companiondevicemanager"
adb shell "pm disable-user --user 0 com.android.cts.priv.ctsshim"
adb shell "pm disable-user --user 0 com.samsung.android.app.spage"
adb shell "pm disable-user --user 0 com.samsung.android.lool"
adb shell "pm disable-user --user 0 com.samsung.android.app.settings.bixby"
adb shell "pm disable-user --user 0 com.android.providers.downloads"
adb shell "pm disable-user --user 0 com.sec.android.app.parser"
adb shell "pm disable-user --user 0 com.android.bluetoothmidiservice"
adb shell "pm disable-user --user 0 com.facebook.appmanager"
adb shell "pm disable-user --user 0 com.google.android.printservice.recommendation"
adb shell "pm disable-user --user 0 com.samsung.android.app.galaxyfinder"
adb shell "pm disable-user --user 0 com.sec.facatfunction"
adb shell "pm disable-user --user 0 com.google.android.captiveportallogin"
adb shell "pm disable-user --user 0 com.android.keychain"
adb shell "pm disable-user --user 0 com.google.android.overlay.gmsconfig.asi"
adb shell "pm disable-user --user 0 com.sec.android.app.DataCreate"
adb shell "pm disable-user --user 0 com.samsung.ipservice"
adb shell "pm disable-user --user 0 com.samsung.android.accessibility.talkback"
adb shell "pm disable-user --user 0 com.google.android.ondevicepersonalization.services"
adb shell "pm disable-user --user 0 com.sec.android.app.magnifier"
adb shell "pm disable-user --user 0 com.android.bookmarkprovider"
adb shell "pm disable-user --user 0 com.samsung.android.wifi.softapwpathree.resources"
adb shell "pm disable-user --user 0 com.samsung.android.samsungpass"
adb shell "pm disable-user --user 0 com.osp.app.signin"
adb shell "pm disable-user --user 0 com.android.sharedstoragebackup"
adb shell "pm disable-user --user 0 com.android.providers.media"
adb shell "pm disable-user --user 0 com.android.providers.blockednumber"
adb shell "pm disable-user --user 0 com.samsung.android.knox.attestation"
adb shell "pm disable-user --user 0 com.knox.vpn.proxyhandler"
adb shell "pm disable-user --user 0 com.samsung.android.smartcallprovider"
adb shell "pm disable-user --user 0 com.sec.bcservice"
adb shell "pm disable-user --user 0 com.android.proxyhandler"
adb shell "pm disable-user --user 0 com.samsung.app.newtrim"
adb shell "pm disable-user --user 0 com.google.android.overlay.modules.permissioncontroller"
adb shell "pm disable-user --user 0 com.android.emergency"
adb shell "pm disable-user --user 0 com.google.android.gms.location.history"
adb shell "pm disable-user --user 0 com.sec.android.app.setupwizardlegalprovider"
adb shell "pm disable-user --user 0 com.google.android.gm"
adb shell "pm disable-user --user 0 com.android.carrierdefaultapp"
adb shell "pm disable-user --user 0 com.android.backupconfirm"
adb shell "pm disable-user --user 0 com.samsung.android.mdm"
adb shell "pm disable-user --user 0 com.google.android.apps.tachyon"
adb shell "pm disable-user --user 0 com.hiya.star"
adb shell "pm disable-user --user 0 com.spectrum.cm.headless"
adb shell "pm disable-user --user 0 com.sec.android.app.personalization"
adb shell "pm disable-user --user 0 com.android.theme.font.notoserifsource"
adb shell "pm disable-user --user 0 com.samsung.android.smartface"
adb shell "pm disable-user --user 0 com.samsung.android.bbc.bbcagent"
adb shell "pm disable-user --user 0 com.samsung.android.shortcutbackupservice"
adb shell "pm disable-user --user 0 com.samsung.android.mcfserver"
adb shell "pm disable-user --user 0 com.android.wallpapercropper"
adb shell "pm disable-user --user 0 com.samsung.android.app.parentalcare"
adb shell "pm disable-user --user 0 com.google.android.overlay.gmsconfig.geotz"
adb shell "pm disable-user --user 0 com.android.internal.systemui.navbar.gestural"
adb shell "pm disable-user --user 0 com.android.settings.intelligence"
adb shell "pm disable-user --user 0 com.sec.android.app.factorykeystring"
adb shell "pm disable-user --user 0 com.samsung.internal.systemui.navbar.sec_gestural"
adb shell "pm disable-user --user 0 com.samsung.android.knox.pushmanager"
adb shell "pm disable-user --user 0 com.sec.android.app.bluetoothagent"
adb shell "pm disable-user --user 0 com.samsung.android.app.watchmanagerstub"
adb shell "pm disable-user --user 0 com.google.android.webview"
adb shell "pm disable-user --user 0 com.android.internal.systemui.navbar.threebutton"
adb shell "pm disable-user --user 0 com.android.egg"
adb shell "pm disable-user --user 0 com.samsung.android.wifi.softap.resources"
adb shell "pm disable-user --user 0 com.samsung.android.aircommandmanager"
adb shell "pm disable-user --user 0 com.samsung.android.networkstack"
adb shell "pm disable-user --user 0 com.google.android.overlay.modules.modulemetadata.forframework"
adb shell "pm disable-user --user 0 com.samsung.android.callbgprovider"
adb shell "pm disable-user --user 0 com.sec.android.easyMover.Agent"
adb shell "pm disable-user --user 0 com.samsung.android.container"
adb shell "pm disable-user --user 0 com.sec.epdg"
adb shell "pm disable-user --user 0 com.samsung.android.bluelightfilter"
adb shell "pm disable-user --user 0 com.samsung.android.wcmurlsnetworkstack"
adb shell "pm disable-user --user 0 com.android.se"
adb shell "pm disable-user --user 0 com.sec.hiddenmenu"
adb shell "pm disable-user --user 0 com.sec.location.nfwlocationprivacy"
adb shell "pm disable-user --user 0 com.android.stk"
adb shell "pm disable-user --user 0 com.samsung.android.mdx.quickboard"
adb shell "pm disable-user --user 0 com.sec.android.app.hwmoduletest"
adb shell "pm disable-user --user 0 com.android.bips"
adb shell "pm disable-user --user 0 com.google.android.partnersetup"
adb shell "pm disable-user --user 0 com.google.android.projection.gearhead"
adb shell "pm disable-user --user 0 com.mediatek.systemuiresoverlay"
adb shell "pm disable-user --user 0 com.sec.android.emergencylauncher"
adb shell "pm disable-user --user 0 com.google.android.apps.carrier.carrierwifi"
adb shell "pm disable-user --user 0 com.sec.android.easyonehand"
adb shell "pm disable-user --user 0 com.samsung.android.setting.multisound"
adb shell "pm disable-user --user 0 com.samsung.android.networkstack.tethering.overlay"
adb shell "pm disable-user --user 0 com.google.android.feedback"
adb shell "pm disable-user --user 0 com.verizon.loginengine.unbranded"
adb shell "pm disable-user --user 0 com.sec.unifiedwfc"
adb shell "pm disable-user --user 0 com.samsung.android.app.taskedge"
adb shell "pm disable-user --user 0 com.sec.android.smartfpsadjuster"
adb shell "pm disable-user --user 0 com.samsung.android.dck.timesync"
adb shell "pm disable-user --user 0 com.samsung.safetyinformation"
adb shell "pm disable-user --user 0 com.android.providers.downloads.ui"
adb shell "pm disable-user --user 0 com.android.ons"
adb shell "pm disable-user --user 0 com.spectrum.Spec_Mobile"
adb shell "pm disable-user --user 0 com.google.android.nearby.halfsheet"
adb shell "pm disable-user --user 0 com.sec.android.app.setupwizard"
adb shell "pm disable-user --user 0 com.samsung.android.allshare.service.fileshare"
adb shell "pm disable-user --user 0 com.samsung.sec.android.application.csc"
adb shell "pm disable-user --user 0 com.google.android.setupwizard"
adb shell "pm disable-user --user 0 com.sec.mhs.smarttethering"
adb shell "pm disable-user --user 0 com.android.simappdialog"
adb shell "pm disable-user --user 0 com.android.wallpaper.livepicker"
adb shell "pm disable-user --user 0 com.samsung.android.dynamiclock"
adb shell "pm disable-user --user 0 com.android.internal.display.cutout.emulation.waterfall"
adb shell "pm disable-user --user 0 com.sec.app.RilErrorNotifier"
adb shell "pm disable-user --user 0 com.samsung.android.privacydashboard"
adb shell "pm disable-user --user 0 com.google.android.overlay.modules.ext.services"
adb shell "pm disable-user --user 0 com.sec.phone"
adb shell "pm disable-user --user 0 com.samsung.android.location"
adb shell "pm disable-user --user 0 com.android.traceur"
adb shell "pm disable-user --user 0 com.samsung.android.samsungpassautofill"
adb shell "pm disable-user --user 0 com.samsung.ims.smk"
adb shell "pm disable-user --user 0 com.sec.android.app.wlantest"
adb shell "pm disable-user --user 0 com.google.android.googlequicksearchbox"
adb shell "pm disable-user --user 0 com.google.android.modulemetadata"
adb shell "pm disable-user --user 0 com.sec.hearingadjust"
adb shell "pm disable-user --user 0 com.samsung.android.knox.containercore"
adb shell "pm disable-user --user 0 com.google.android.ext.services"
adb shell "pm disable-user --user 0 com.google.android.configupdater"
adb shell "pm disable-user --user 0 com.samsung.android.forest"
adb shell "pm disable-user --user 0 com.sec.factory.cameralyzer"
adb shell "pm disable-user --user 0 com.google.android.gms.supervision"
adb shell "pm disable-user --user 0 com.samsung.ssu"
adb shell "pm disable-user --user 0 com.samsung.android.authfw"
adb shell "pm disable-user --user 0 com.samsung.android.ipsgeofence"
adb shell "pm disable-user --user 0 com.android.internal.display.cutout.emulation.corner"
adb shell "pm disable-user --user 0 com.sec.android.app.soundalive"
adb shell "pm disable-user --user 0 com.android.printspooler"
adb shell "pm disable-user --user 0 com.samsung.android.service.peoplestripe"
adb shell "pm disable-user --user 0 com.samsung.klmsagent"
adb shell "pm disable-user --user 0 com.facebook.system"
adb shell "pm disable-user --user 0 com.google.mainline.telemetry"
adb shell "pm disable-user --user 0 com.samsung.android.hdmapp"
adb shell "pm disable-user --user 0 com.samsung.android.ardrawing"
adb shell "pm disable-user --user 0 com.sec.android.app.billing"
adb shell "pm disable-user --user 0 com.samsung.android.mdx.kit"
adb shell "pm disable-user --user 0 com.samsung.android.app.dofviewer"
adb shell "pm disable-user --user 0 com.samsung.android.da.daagent"
adb shell "pm disable-user --user 0 com.samsung.unifiedtp"
adb shell "pm disable-user --user 0 com.google.audio.hearing.visualization.accessibility.scribe"
adb shell "pm disable-user --user 0 com.samsung.android.wifi.resources"
adb shell "pm disable-user --user 0 com.samsung.android.svcagent"
adb shell "pm disable-user --user 0 com.samsung.android.widget.pictureframe"
adb shell "pm disable-user --user 0 com.sec.automation"
adb shell "pm disable-user --user 0 com.mediatek.MtkSettingsResOverlay"
adb shell "pm disable-user --user 0 com.sec.android.app.servicemodeapp"
adb shell "pm disable-user --user 0 com.wssyncmldm"
adb shell "pm disable-user --user 0 com.sec.enterprise.mdm.services.simpin"
adb shell "pm disable-user --user 0 com.android.calllogbackup"
adb shell "pm disable-user --user 0 com.samsung.android.providers.factory"
adb shell "pm disable-user --user 0 com.google.android.overlay.modules.cellbroadcastreceiver"
adb shell "pm disable-user --user 0 com.sec.android.app.samsungapps"
adb shell "pm disable-user --user 0 com.samsung.android.app.appsedge"
adb shell "pm disable-user --user 0 com.sec.android.diagmonagent"
adb shell "pm disable-user --user 0 com.sec.providers.assisteddialing"
adb shell "pm disable-user --user 0 com.android.dreams.basic"
adb shell "pm disable-user --user 0 com.google.android.cellbroadcastreceiver"
adb shell "pm disable-user --user 0 com.samsung.sec.android.teegris.tui_service"
adb shell "pm disable-user --user 0 com.samsung.android.app.sharelive"
adb shell "pm disable-user --user 0 com.samsung.android.localeoverlaymanager"
adb shell "pm disable-user --user 0 com.google.android.adservices.api"
adb shell "pm disable-user --user 0 com.samsung.android.spayfw"
adb shell "pm disable-user --user 0 com.samsung.android.themestore"
adb shell "pm disable-user --user 0 com.android.inputdevices"
adb shell "pm disable-user --user 0 com.mediatek.FrameworkResOverlayExt"
adb shell "pm disable-user --user 0 com.sec.android.mimage.avatarstickers"
adb shell "pm disable-user --user 0 com.sec.sve"
adb shell "pm disable-user --user 0 com.samsung.vvm"
adb shell "pm disable-user --user 0 com.google.android.onetimeinitializer"
adb shell "pm disable-user --user 0 com.android.apps.tag"
adb shell "pm disable-user --user 0 com.samsung.InputEventApp"
adb shell "pm disable-user --user 0 com.mediatek.SettingsProviderResOverlay"
adb shell "pm disable-user --user 0 com.samsung.android.sdk.handwriting"
adb shell "pm disable-user --user 0 com.sec.android.sdhms"
adb shell "pm disable-user --user 0 com.mediatek.apmonitor"
adb shell "pm disable-user --user 0 com.google.android.overlay.modules.documentsui"
adb shell "pm disable-user --user 0 com.mtk.android.networkstack.tethering.overlay"
adb shell "pm disable-user --user 0 com.samsung.android.networkdiagnostic"
adb shell "pm disable-user --user 0 com.mediatek"
adb shell "pm disable-user --user 0 com.android.managedprovisioning"
adb shell "pm disable-user --user 0 com.mtk.android.networkstack.tethering.inprocess.overlay"
adb shell "pm disable-user --user 0 com.samsung.advp.imssettings"
adb shell "pm disable-user --user 0 com.samsung.android.biometrics.app.setting"
adb shell "pm disable-user --user 0 com.mediatek.mdmlsample"
adb shell "pm disable-user --user 0 com.samsung.sait.sohservice"
adb shell "pm disable-user --user 0 com.samsung.android.ConnectivityUxOverlay"
adb shell "pm disable-user --user 0 com.android.nfc"
adb shell "pm disable-user --user 0 com.google.android.gsf"
adb shell "pm disable-user --user 0 com.samsung.knox.securefolder"
adb shell "pm disable-user --user 0 com.android.internal.display.cutout.emulation.double"
adb shell "pm disable-user --user 0 com.mediatek.frameworkresoverlay"
adb shell "pm disable-user --user 0 com.sec.epdgtestapp"
adb shell "pm disable-user --user 0 com.google.android.syncadapters.calendar"
adb shell "pm disable-user --user 0 com.samsung.android.cidmanager"
adb shell "pm disable-user --user 0 com.google.android.overlay.modules.cellbroadcastservice"
adb shell "pm disable-user --user 0 com.samsung.android.scloud"
adb shell "pm disable-user --user 0 com.google.ar.core"
adb shell "pm disable-user --user 0 com.microsoft.skydrive"
adb shell "pm disable-user --user 0 com.samsung.android.game.gametools"
adb shell "pm disable-user --user 0 com.samsung.android.beaconmanager"
adb shell "pm disable-user --user 0 com.samsung.android.appseparation"
adb shell "pm disable-user --user 0 com.google.mainline.adservices"
adb shell "pm disable-user --user 0 com.samsung.android.app.cocktailbarservice"
adb shell "pm disable-user --user 0 com.samsung.android.privateshare"
adb shell "pm disable-user --user 0 com.monotype.android.font.samsungone"
adb shell "pm disable-user --user 0 com.samsung.android.video"
adb shell "pm disable-user --user 0 com.samsung.android.audiomirroring"
adb shell "pm disable-user --user 0 com.pocketgeek.android"
adb shell "pm disable-user --user 0 com.wsomacp"
adb shell "pm disable-user --user 0 com.android.wallpaperbackup"
adb shell "pm disable-user --user 0 com.samsung.android.app.soundpicker"
adb shell "pm disable-user --user 0 com.samsung.clipboardsaveservice"
adb shell "pm disable-user --user 0 com.samsung.android.app.omcagent"
adb shell "pm disable-user --user 0 com.android.localtransport"
adb shell "pm disable-user --user 0 com.samsung.SMT"
adb shell "pm disable-user --user 0 com.samsung.cmh"
adb shell "pm disable-user --user 0 com.sec.android.app.volumemonitorprovider"
adb shell "pm disable-user --user 0 com.mediatek.cellbroadcastuiresoverlay"
adb shell "pm disable-user --user 0 com.samsung.android.app.clipboardedge"
adb shell "pm disable-user --user 0 com.samsung.android.aware.service"
adb shell "pm disable-user --user 0 com.sec.android.CcInfo"
adb shell "pm disable-user --user 0 com.android.pacprocessor"
adb shell "pm disable-user --user 0 com.google.android.safetycenter.resources"
adb shell "pm disable-user --user 0 com.samsung.android.app.reminder"
adb shell "pm disable-user --user 0 com.sec.factory.camera"
adb shell "pm disable-user --user 0 com.sec.enterprise.knox.cloudmdm.smdms"
adb shell "pm disable-user --user 0 com.android.internal.display.cutout.emulation.hole"
adb shell "pm disable-user --user 0 com.android.internal.systemui.navbar.gestural_narrow_back"
adb shell "pm disable-user --user 0 com.android.internal.display.cutout.emulation.tall"
adb shell "pm disable-user --user 0 android.autoinstalls.config.samsung"
adb shell "pm disable-user --user 0 com.android.cameraextensions"
adb shell "pm disable-user --user 0 com.sec.android.app.SecSetupWizard"
adb shell "pm disable-user --user 0 com.sec.location.nsflp2"
adb shell "pm disable-user --user 0 com.samsung.android.app.telephonyui"
adb shell "pm disable-user --user 0 com.android.carrierconfig"
adb shell "pm disable-user --user 0 com.samsung.android.keycustomizationinfobackupservice"
adb shell "pm disable-user --user 0 com.android.internal.systemui.navbar.gestural_wide_back"
adb shell "pm disable-user --user 0 com.android.internal.systemui.onehanded.gestural"
adb shell "pm disable-user --user 0 com.google.android.ext.shared"
adb shell "pm disable-user --user 0 com.samsung.android.wifi.h2e.resources"
adb shell "pm disable-user --user 0 com.android.chrome"
adb shell "pm disable-user --user 0 com.facebook.services"
adb shell "pm disable-user --user 0 com.google.android.apps.maps"
adb shell "pm disable-user --user 0 com.samsung.android.provider.filterprovider"
adb shell "pm disable-user --user 0 com.sec.android.app.ve.vebgm"
adb shell "pm disable-user --user 0 com.google.android.as"
adb shell "pm disable-user --user 0 com.samsung.android.samsungpositioning"
adb shell "pm disable-user --user 0 android.auto_generated_rro_product__"
adb shell "pm disable-user --user 0 com.mtk.google.android.networkstack.tethering.overlay"
adb shell "pm disable-user --user 0 com.samsung.android.server.wifi.mobilewips"
adb shell "pm disable-user --user 0 com.samsung.android.smartswitchassistant"
adb shell "pm disable-user --user 0 com.samsung.android.knox.analytics.uploader"
adb shell "pm disable-user --user 0 com.samsung.android.wallpaper.res"
adb shell "pm disable-user --user 0 com.samsung.android.dqagent"
adb shell "pm disable-user --user 0 com.samsung.android.arzone"
adb shell "pm disable-user --user 0 com.samsung.android.fmm"
adb shell "pm disable-user --user 0 com.android.certinstaller"
adb shell "pm disable-user --user 0 com.samsung.aasaservice"
adb shell "pm disable-user --user 0 com.android.wifi.dialog"
adb shell "pm disable-user --user 0 com.sec.android.app.safetyassurance"
adb shell "pm disable-user --user 0 com.google.android.apps.restore"
adb shell "pm disable-user --user 0 com.sec.android.app.chromecustomizations"
adb shell "pm disable-user --user 0 com.samsung.android.easysetup"
adb shell "pm disable-user --user 0 com.samsung.android.stickercenter"
adb shell "pm disable-user --user 0 com.sec.spp.push"
adb shell "pm disable-user --user 0 com.samsung.android.aremojieditor"
adb shell "pm disable-user --user 0 com.samsung.faceservice"
adb shell "pm disable-user --user 0 com.android.internal.systemui.navbar.gestural_extra_wide_back"
adb shell "pm disable-user --user 0 com.sec.android.app.quicktool"
adb shell "pm disable-user --user 0 com.google.android.as.oss"
adb shell "pm disable-user --user 0 com.monotype.android.font.foundation"
adb shell "pm disable-user --user 0 com.android.vpndialogs"
adb shell "pm disable-user --user 0 com.android.uwb.resources"
adb shell "pm disable-user --user 0 com.google.android.overlay.gmsconfig.photos"
adb shell "pm disable-user --user 0 com.google.android.tts"
adb shell "pm disable-user --user 0 com.mediatek.batterywarning"
adb shell "pm disable-user --user 0 com.android.htmlviewer"
adb shell "pm disable-user --user 0 com.samsung.android.app.updatecenter"
adb shell "pm disable-user --user 0 com.android.vending"
adb shell "pm disable-user --user 0 com.samsung.android.sdm.config"
adb shell "pm disable-user --user 0 com.sec.android.daemonapp"
adb shell "pm disable-user --user 0 com.samsung.android.themecenter"
adb shell "pm disable-user --user 0 com.google.android.overlay.modules.captiveportallogin.forframework"
adb shell "pm disable-user --user 0 com.samsung.android.aremoji"
adb shell "pm disable-user --user 0 com.google.android.apps.turbo"
adb shell "pm disable-user --user 0 com.samsung.android.mobileservice"
adb shell "pm disable-user --user 0 com.samsung.android.wifi.p2paware.resources"
adb shell "pm disable-user --user 0 com.sec.usbsettings"
adb shell "pm disable-user --user 0 com.google.android.overlay.gmsconfig.gsa"
adb shell "pm disable-user --user 0 com.samsung.android.service.stplatform"
adb shell "pm disable-user --user 0 com.sec.vsim.ericssonnsds.webapp"
adb shell "pm disable-user --user 0 com.android.providers.userdictionary"
adb shell "pm disable-user --user 0 com.google.android.overlay.gmsconfig.common"
adb shell "pm disable-user --user 0 com.android.cts.ctsshim"
adb shell "pm disable-user --user 0 com.android.bluetooth"
adb shell "pm disable-user --user 0 com.samsung.storyservice"
adb shell "pm disable-user --user 0 com.samsung.internal.systemui.navbar.gestural_no_hint"
adb shell "pm disable-user --user 0 com.samsung.android.game.gos"
adb shell "pm disable-user --user 0 com.samsung.android.app.smartcapture"
adb shell "pm disable-user --user 0 com.skms.android.agent"
adb shell "pm disable-user --user 0 com.samsung.android.ConnectivityOverlay"
adb shell "pm disable-user --user 0 com.sec.android.soagent"
adb shell "pm disable-user --user 0 com.android.providers.partnerbookmarks"
adb shell "pm disable-user --user 0 com.samsung.sdm"
adb shell "pm disable-user --user 0 com.samsung.android.kidsinstaller"
adb shell "pm disable-user --user 0 com.mediatek.gbaservice"
adb shell "pm disable-user --user 0 com.samsung.android.mdecservice"
adb shell "pm disable-user --user 0 com.facebook.katana"
adb shell "pm disable-user --user 0 com.mediatek.entitlement.fcm"
adb shell "pm disable-user --user 0 com.android.dynsystem"
adb shell "pm disable-user --user 0 com.samsung.android.game.gamehome"
adb shell "pm disable-user --user 0 com.samsung.android.providers.media"
adb shell "pm disable-user --user 0 com.samsung.android.rubin.app"
adb shell "pm disable-user --user 0 com.android.hotspot2.osulogin"
adb shell "pm disable-user --user 0 com.sec.android.mimage.photoretouching"
adb shell "pm disable-user --user 0 com.google.android.youtube"
adb shell "pm disable-user --user 0 com.samsung.android.gru"
adb shell "pm disable-user --user 0 com.samsung.android.scpm"
adb shell "pm disable-user --user 0 com.test.LTEfunctionality"
::adb shell "pm disable-user --user 0 com.samsung.android.peripheral.framework"
::adb shell "pm disable-user --user 0 com.samsung.cmfa.AuthTouch"
::adb shell "pm disable-user --user 0 com.samsung.android.cmfa.framework"
::nstr
::com.google.android.documentsui  :::::::NSTR:::::::::
::com.sec.android.app.clockpackage  :::::::NSTR:::::::::
::com.google.android.networkstack.tethering  :::::::NSTR:::::::::
::com.android.providers.settings  :::::::NSTR:::::::::
::com.google.android.networkstack.tethering.overlay  :::::::NSTR:::::::::
::com.android.phone  :::::::NSTR:::::::::
::com.samsung.android.dialer  :::::::NSTR:::::::::
::com.samsung.android.messaging  :::::::NSTR:::::::::
::com.samsung.android.incallui  :::::::NSTR:::::::::
::com.samsung.android.secsoundpicker  :::::::NSTR:::::::::
::com.google.android.permissioncontroller  :::::::NSTR:::::::::
::com.android.wifi.resources  :::::::NSTR::::::::: 
::com.android.server.telecom  :::::::NSTR:::::::::
::com.google.android.connectivity.resources  :::::::NSTR:::::::::
::com.google.android.cellbroadcastservice  :::::::NSTR:::::::::
::com.google.android.providers.media.module  :::::::NSTR:::::::::
::com.samsung.android.providers.contacts :::::::NSTR:::::::::
::com.google.android.sdksandbox  :::::::NSTR:::::::::
::com.samsung.android.kgclient  :::::::NSTR:::::::::
::com.android.location.fused  :::::::NSTR:::::::::
::com.samsung.android.mtp  :::::::NSTR:::::::::
::com.android.mtp  :::::::NSTR:::::::::
::com.sec.android.app.launcher  :::::::NSTR:::::::::
::com.google.android.gms  :::::::NSTR:::::::::
::com.android.settings  :::::::NSTR:::::::::
::com.samsung.android.app.dressroom  :::::::NSTR:::::::::
::com.sec.imsservice  :::::::NSTR:::::::::
::com.sec.imslogger  :::::::NSTR:::::::::
::com.sec.android.app.sbrowser  :::::::NSTR:::::::::
::com.sec.android.app.myfiles  :::::::NSTR:::::::::
::com.samsung.android.app.contacts  :::::::NSTR:::::::::
::com.sec.android.provider.badge  :::::::NSTR:::::::::
::com.sec.android.app.camera  :::::::NSTR:::::::::
::com.sec.android.gallery3d  :::::::NSTR:::::::::
::com.google.android.packageinstaller  :::::::NSTR:::::::::
::com.samsung.android.honeyboard  :::::::NSTR:::::::::
::com.android.providers.calendar  :::::::NSTR:::::::::
::com.samsung.android.calendar   :::::::NSTR:::::::::
::com.android.shell  :::::::NSTR:::::::::
::com.android.systemui  :::::::NSTR:::::::::
::com.android.externalstorage
::com.samsung.accessibility
::com.samsung.adaptivebrightnessgo
::com.android.mms.service
::com.samsung.android.emergency
::com.android.storagemanager 
::com.android.providers.telephony
::com.google.android.networkstack
::osmand  ::maps gps
::major  ::appinfo
::android
::com.samsung.android.app.clockpack
::com.samsung.android.app.routines
